# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  anchorpr.whitebox.cerberus.dev:

networks:
  cerberusntw:

services:

  couchdb.anchorpr.whitebox:
    container_name: couchdb.anchorpr.whitebox
    image: hyperledger/fabric-couchdb:$IMAGE_TAG
    # Populate the COUCHDB_USER and COUCHDB_PASSWORD to set an admin user and password
    # for CouchDB.  This will prevent CouchDB from operating in an "Admin Party" mode.
    environment:
      - COUCHDB_USER=useranchorprwhitebox
      - COUCHDB_PASSWORD=passwordanchorprwhitebox
    # Comment/Uncomment the port mapping if you want to hide/expose the CouchDB service,
    # for example map it to utilize Fauxton User Interface in dev environments.
    ports:
      - 13044:5984
    networks:
      - cerberusntw

  anchorpr.whitebox.cerberus.dev:
    extends:
      file: organizations/whitebox/whitebox-base.yaml
      service: anchorpr.whitebox.cerberus.dev
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb.anchorpr.whitebox:5984
      # The CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME and CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD
      # provide the credentials for ledger to connect to CouchDB.  The username and password must
      # match the username and password set for the associated CouchDB.
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=useranchorprwhitebox
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=passwordanchorprwhitebox
    depends_on:
      - couchdb.anchorpr.whitebox


