# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#


# NOTE: This is not the way a Kafka cluster would normally be deployed in production, as it is not secure
# and is not fault tolerant. This example is a toy deployment that is only meant to exercise the Kafka code path
# of the ordering service.

version: '2'

networks:
  ntwcerberus:

services:

  zookeeper:
    image: hyperledger/fabric-zookeeper:$IMAGE_TAG
    restart: always
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      OOKEEPER_TICK_TIME: 2000

    ports:
      - 2181
      - 2888
      - 3888
      - 4888
      - 5888
      - 6888
      - 7888


  kafka:
    image: hyperledger/fabric-kafka:$IMAGE_TAG
    restart: always
    environment:
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=2
      - KAFKA_MESSAGE_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_REPLICA_FETCH_MAX_BYTES=1048576 # 1 * 1024 * 1024 B
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=2